###  Islands: Python Foundations - Chapter 3

[Back to Main Page](0_main_page.ipynb)

[How to use this book interactively on Deepnote](99_how_to_use_this_book.ipynb)

[Download this book](99_how_to_use_this_book_local.ipynb)

<br>

<h1> <center> Arrays & Boolean Indexing </center> </h1> 

## Importing Libraries

As before, the cell below imports the libraries we need. 

Once again, <b> it is very important you run each cell in this notebook in the order in which they appear. </b> Later cells depend on the activity of earlier cells. 

<br>
<br>
<center> ↓↓↓ <b> Before reading on, please run the cell below</b>. Click on the cell and press `shift` and `Enter` together.↓↓↓ </center>

In [1]:
# run this cell (by pressing 'Control' and 'Enter' together) to import the libraries needed for 
# this page

# 'import' tells python to get a set of functions (which is called a library), in the first case this is 
# the numpy library. The 'as' tells python to name the library something (to save us typing out 'numpy'); in this case
# we name the library 'np'
import numpy as np

# in this case we import the pandas library and name it 'pd'
import pandas as pd

# here we import the matplotlib.pyplot library and name it 'plt'
import matplotlib.pyplot as plt

# this imports the machinery for marking answers to questions
from client.api.notebook import Notebook
ok = Notebook('ok_tests/3_arrays_booleans.ok')

# generating the data for this page
import py_found

psychosis_status_observations, observations_sex, psychosis_scores, names = py_found.arrays_booleans_page_setup()

Assignment: 3_arrays_booleans
OK, version v1.18.1



## Comparisons and Booleans

We mentioned earlier that python is useful for representing things in the world, and the relations between those things. We can use ```comparison operators``` to ask questions about the relations between differnt collections of data.

Consider the following list, which contains the names of the 5 people who were in the first sample of observations that your research group made on the island:

In [2]:
names

['roy', 'david', 'lucy', 'aiesha', 'amelia']

We can see that the third person we observed is called `lucy`. We know that to access this element of the ```names``` list, we would use ```names[2]``` (remember that Python begins counting at 0, so the index of the third element in a list is 2):

In [3]:
names[2]

'lucy'

The ```==``` operator in python asks the question 'is this value equal to another value?'. 

Our psychiatrist friend asks us *'what was the name of the third person we observed? Was it Lucy?'*. 

The code in the cell below asks the question 'is the third element of the ```names``` list equal to the value ```lucy```'?

In [4]:
names[2] == 'lucy'

True

Look at the ```names``` list above. We can see that ```'roy``` is the first name in the list. Therefore, we, as humans, can see that it is <b>not</b> the case that ```'roy'``` is the third element in the ```names``` list. Let's ask Python if ```'roy'``` is the third element of the ```names``` list:

In [5]:
names[2] == 'roy'

False

### Question 1

In the cell below, yse the `==` comparison operator to ask *'is the 5th element of the `names` list equal to 'david'?'. Store your answer in a variable called `is_it_david`:

In [6]:
is_it_david = names[4] == 'david' #!!! replace with ...

# show the value
is_it_david

False

In [7]:
_ = ok.grade('q1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 2
    Failed: 0
[ooooooooook] 100.0% passed



The values ```True``` and ```False``` are a specific data type: they are Booleans. If you use a comparison operator to ask python a question about the relations between two values, it will always return a Boolean - a ```True``` or ```False```.

In [8]:
type(True)

bool

In [9]:
type(False)

bool

Notice that the Boolean values ```True``` and ```False``` do not have quotation marks around them. What type do you think they would be if they had quotation marks around them?

In [10]:
type('True') 

str

There are other comparison operators, which ask different questions to ```==```. For instance:

```!=```  - asks *'are these two values NOT equal?*

```names[3]``` has the value ```'aiesha'```, which is not the same value as ```lucy```. 

Our psychiatrist friend asks us *`the fourth person we observed wasn't called Lucy, is that correct?'*. So we ask Python:

In [11]:
# this code asks 'is the fourth element in the observations list NOT EQUAL to 'lucy'?
names[3] != 'lucy' 

True

### Question 2

Find out what value ```names[2]``` has. Ask python 'is ```names[2]``` NOT EQUAL to ```'lucy'```? Store the result in a variable called `ans_lucy`:

In [12]:
names

['roy', 'david', 'lucy', 'aiesha', 'amelia']

In [13]:
# your code here
ans_lucy =  names[2] != 'lucy' #!!! replace with ...

# this line just makes the cell output whatever value you have saved in the ans_lucy variable
ans_lucy  

False

In [14]:
_ = ok.grade('q2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 2
    Failed: 0
[ooooooooook] 100.0% passed



Recall the `psychosis_scores` list, which contains the psychosis questionairre scores for the first five individuals sampled on the island:

In [15]:
# run this cell to see the contents of the list
psychosis_scores

[80, 20, 14, 13, 91]

The psychiatrist tells you that, for the questionnaire being used, the cutoff score for identifying that an individual is experiencing a psychotic episode is 70.

The comparison operator `>=` asks 'is the value on the left hand side of the operator greater than or equal to the value on the right hand side?'.

So if we wanted to ask 'is 50 greater than or equal to 100?', we would write:

In [16]:
# run this cell
50 >= 100

False

You can see that this operator returns a Boolean, indicating the answer to the question we asked it.

### Question 3

Using python, how would you ask:
> *'did the fifth person we sampled have a score above the cutoff of 70, indicating they were experiencing a psychotic episode?'*. 

Store your answer in a variable called `fifth_psychosis`:

In [17]:
fifth_psychosis = psychosis_scores[4] > 70 #!!! replace with ...

# this line just makes the cell output whatever value you have saved in the fifth_psychosis variable
fifth_psychosis 

True

In [18]:
_ = ok.grade('q3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 2
    Failed: 0
[ooooooooook] 100.0% passed



## Numpy arrays and Boolean Indexing

What if we want to see all of the elements of the `psychosis_scores` list which are greater than 70? 

Could we use `psychosis_scores > 70`? 

In [19]:
psychosis_scores > 70

TypeError: '>' not supported between instances of 'list' and 'int'

If you look at the error message that `psychosis_scores > 70` generates, it is clear that `>` will not work to compare all the elements of a list with a given value.

This is annoying because a lot of questions we might want to investigate will need that sort of operation. For instance, calculating the prevalence of psychotic disorders on the island will require calculating how many islanders have a psychotic disorder. If the `psychosis_scores` list containing the scores of all 10,000 islanders, then working out how many of those scores were over 70 would be essential to calculating the prevalence.

Fortunately, there is a way of using comparison operators like `>` on multiple elements. We need to convert the list to a *numpy array*. This is very much like a list, but has useful properties that let us do things we cannot do with lists.

We will come to functions on the [next page](4_functions_plotting.ipynb), for now, just think of a function as a command that tells python to do something.

The function `np.array()` - when we put a list between the brackets - tells Python to convert that list into an array. The function is from the [numpy](https://numpy.org/about/) library. The code in the cell below that reads `import numpy as np` imports the numpy library, and names it `np` so that we can access it without having to type `numpy` every time.

The code that reads `np.array([psychosis_scores])` uses the `np.array()` function to convert the `psychosis_scores` list into a numpy array:

In [ ]:
# just run this cell

import numpy as np

np.array([psychosis_scores])

Run the cell below to save the converted list in a variable called `psychosis_scores_array`:

In [20]:
# just run this cell
psychosis_scores_array = np.array([psychosis_scores])

# show the array
psychosis_scores_array

array([[80, 20, 14, 13, 91]])

Now let's see what happens if we use the `>` comparison operation to show the elements of the `psychosis_scores_array` which are greater than the cutoff of 70:

In [ ]:
psychosis_scores_array > 70

The array: `array([[ True, False, False, False,  True]])` is called a *Boolean array* because it contains only Boolean values (`True` or `False`). This array is `True` where the corresponding element in the `psychosis_scores_array` was greater than 70, and `False` otherwise.

Boolean arrays are essential to data science analysis. They allow a user to find values which meet or do not meet some condition.

Let's store the Boolean array that we have just created as a variable called `greater_than_70`:

In [ ]:
greater_than_70 = psychosis_scores_array > 70

# show the array

greater_than_70

Remember that we generated this array using the following code:

> `psychosis_scores_array > 70`

Let's compare the Boolean array to the original `psychosis_scores_array`:

In [ ]:
# just run this cell
print(psychosis_scores_array)
print(psychosis_scores_array > 70)

The output of the cell above shows two arrays. The first array (containing only integers) is the original `psychosis_scores_array`. The second array (containing only `True`'s and `False`'s) is the Boolean array created using `psychosis_scores_array > 70`.

If you look at the first values in each array (80 and `True`) you can see that the Boolean array has a `True` as its first element because the first element of the `psychosis_scores_array` is greater than 70.

If you look at the second values in each array (20 and `False`) you can see that the Boolean array has a `False` as its second element because the second element of the `psychosis_scores_array` is greater than 70.

You get the idea, this is the case at every location of each array: the element of the Boolean array will be `True` if the corresponding element of the `psychosis_scores_array` is greater than 70. 

If we generate a Boolean array in this way (e.g. by using a comparison operator on an array containing some data), we can then use that Boolean array to return only the elements of the original array which are `True` in the Boolean array. 

To make this clearer, let's look at the original array and the Boolean array side-by-side:

In [ ]:
# just run this cell
print(psychosis_scores_array)
print(psychosis_scores_array > 70)

If we use the Boolean array to index the original array, then the `True`'s and `False`'s act as 'switches' and 'turn off' the values which correspond to a false, and 'turn on' the values which correspond to a `True`:

In [ ]:
psychosis_scores_array[psychosis_scores_array > 70]

80 and 91 are the values from the `psychosis_scores_array` which are above 70, and therefore the corresponding elements of the Boolean array are `True`. You can see that `[20, 14, 13]` got 'switched off' by the Boolean array, as their corresponding elements were `False`:

In [ ]:
# just run this cell
print(psychosis_scores_array)
print(psychosis_scores_array > 70)

Using a Boolean array to index another array is called *Boolean indexing*.

## Question 4

Use the `<` comparison operator on the `psychosis_scores_array` to generate a Boolean array which is `True` where an element of the `psychosis_scores_array` is *less than* 70, and `False` otherwise. Save the Boolean array as a variable called `less_than_70_boolean_array`:

In [30]:
less_than_70_boolean_array = psychosis_scores_array < 70 #!!! replace with...

# show the array
less_than_70_boolean_array

array([[False,  True,  True,  True, False]])

In [31]:
_ = ok.grade('q4')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 2
    Failed: 0
[ooooooooook] 100.0% passed



Compare the Boolean array that you have just created with the `psychosis_scores_array` shown below. Compare the elements at each position of each array (e.g. the first element each array, the second element of each array etc...) as before: 

In [32]:
 psychosis_scores_array

array([[80, 20, 14, 13, 91]])

Remember that the `True`'s and `False`'s will act as switches if you use the `less_than_70_boolean_array` to index the `psychosis_scores_array`. Any values that correspond to a `False` will be 'switched off' and only values corresponding to a `True` will make it through.

In [33]:
# type your answer below

# the values that will make it into the new array are...

## Question 5

In [34]:
scores_less_than_70 = psychosis_scores_array[less_than_70_boolean_array]

# show the array
scores_less_than_70 

array([20, 14, 13])

In [35]:
_ = ok.grade('q5')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 2
    Failed: 0
[ooooooooook] 100.0% passed



## Question 6

Create a Boolean array called `very_low_scores_boolean_array` which is `True` where `psychosis_scores_array` is *less than or equal to* 14.

Hint: `<=` is the comparison operator meaning 'less than or equal to'.

In [36]:
# compare Boolean array to psychosis scores array 
very_low_scores_boolean_array = psychosis_scores_array <= 14 #!!! replace with ...

# show the array
very_low_scores_boolean_array

array([[False, False,  True,  True, False]])

In [37]:
_ = ok.grade('q6')

InvalidTestInQuestionListException: Test "q6" not found
Did you mean one of the following? (Names are case sensitive)
    q1
    q2
    q3
    q4
    q5

In [ ]:
psychosis_status_observations_array = np.array(psychosis_status_observations)

# show the array
psychosis_status_observations_array

In [ ]:
is_psychotic = psychosis_status_observations_array == 'psychotic'

# show the array
is_psychotic_boolean_array

In [ ]:
_ = ok.grade('q5')

## Question 7 

[SAME STRUCTURE AS QUESTION ABOVE, MANUALLY IDENTIFY ELEMENTS THEN GET THEM WITH BOOLEAN INDEXING]

psychosis_status_observations_array

In [ ]:
_ = ok.grade('q6')

## Question 8

In [ ]:
observations_sex_array = np.array(observations_sex)

# show the array 
observations_sex_array

In [ ]:
is_male_boolean_array = observations_sex_array == 'male' #!!! replace with ...

males = observations_sex_array[is_male_boolean_array]

# show the males array
males

In [ ]:
_ = ok.grade('q7')

In [ ]:
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("ok_tests/3_arrays_booleans") if q.startswith('q')]

Or, you can [return to the main page](0_main_page.ipynb).

To navigate to any other page, the table of contents is below:

## Other Chapters

1. [Populations, Samples & Questions: Why Learn Python?](1_populations_samples_questions.ipynb)
2. [Lists & Indexing](2_lists_indexing.ipynb)
3. [Arrays & Boolean Indexing](3_arrays_booleans.ipynb)
4. [Functions & Plotting](4_functions_plotting.ipynb)
5. [For Loops - doing things over (and over and over...)](5_for_loops.ipynb)
6. [Testing via Simulation: Psychosis Prevalence](6_simulation_psychosis_prevalence.ipynb)

***
By [pxr687](99_about_the_author.ipynb) 